### ISSUE TITLE
Listing all volunteers show error message

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#100]
**Describe the bug**
According to the user guide, "list" command will list all the volunteers in the volunteer pool. Tried it with/without a person in the volunteers list but being shown "Unknown command"

**To Reproduce**
1. list

**Expected behavior**
All the volunteers are listed with no error message shown.

<hr>

**Reported by:** @cheahzk
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#164]</sub>

**Comment by ndhuu** [comment]
This is due to yet-updated UG, we will update accordingly. Thank you.
