### ISSUE TITLE
list is an unknown command

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#101]
**Describe the bug**
Entering list results in an unknown command exception instead of listing the volunteers, as is written in the user guide.

**To Reproduce**
1. Enter list as a command.
2. Unknown command exception is given.

**Expected behavior**
The list command should return the list of volunteers, as written in the user guide.

<hr>

**Reported by:** @justin-ong
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#174]</sub>

**Comment by ndhuu** [comment]
This is due to yet-updated UG, we will update accordingly. Thank you.
