### ISSUE TITLE
find is an invalid command

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#102]
**Describe the bug**
The find command returns an unknown command exception, rather than searching for volunteers.

**To Reproduce**
1. Add a volunteer.
2. Use the find command.
3. Unknown command exception.

**Expected behavior**
The find command should be a usable command, as written in the user guide.

<hr>

**Reported by:** @justin-ong
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#188]</sub>

**Comment by ndhuu** [comment]
This is due to yet-updated UG, we will update accordingly. Thank you.
