### ISSUE TITLE
select is an unknown command

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#104]
**Describe the bug**
The select command returns an unknown command exception, rather than selecting the indexed volunteer.

**To Reproduce**
1. Add a volunteer.
2. Attempt to select the volunteer.
3. Unknown command exception.

**Expected behavior**
The command should work as specified in the user guide.

<hr>

**Reported by:** @justin-ong
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#214]</sub>

**Comment by swalahlah** [comment]
Command Removed!
