### ISSUE TITLE
Documentations to be uploaded for v1.4

### ISSUE THREAD

**Issue by quinnzzzzz** [cs2113-ay1819s2-t08-1/main#124]
**person tagged to ensure job is done**
--to LumiNUS--
Jar file [team][product name].jar - @quinnzzzzz 
UG [TEAM_ID][product Name]UserGuide.pdf - @quinnzzzzz 
DG [TEAM_ID]product Name]DeveloperGuide.pdf - @ndhuu @swalahlah 
--github.io--
Product Website - README page, Ui.png, AboutUs page - @articstranger 
--both--
*Individual PPP [TEAM_ID][Your Name]Portfolio.pdf

**Comment by ndhuu** [comment]
I've updated my parts. Tks Quinn

**Comment by articstranger** [comment]
I will collate and format the user guide for everyone
