### ISSUE TITLE
list command does not work

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#87]
**Describe the bug**
List command is suppose to list all volunteers but when list command is executed, unknown command is in result panel despite having 1 volunteer in the list.

**To Reproduce**
1. add afew volunteers with the addVolunteer command.
2. go to command line and input 'list'

**Expected behavior**
A list of all the volunteer should be shown and result panel should not be unknown command.

**Screenshots**
![image](https://user-images.githubusercontent.com/35758355/55453165-5f016000-560d-11e9-858f-fc88bf534cad.png)
<img width="1440" alt="Screen Shot 2019-04-03 at 12 38 03 PM" src="https://user-images.githubusercontent.com/35758355/55453177-6d4f7c00-560d-11e9-9c0a-c9009043378b.png">

**Additional context**

<hr>

**Reported by:** @jemine1998
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#24]</sub>

**Comment by ndhuu** [comment]
That is due to incomplete UG, which is fixed here #124
