### ISSUE TITLE
editProject command does not work

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#90]
**Describe the bug**
With a project already added,when editProject command is executed, the result display shows unknown command.

**To Reproduce**
1. Add a project with addProject command 
2. Edit project with editProject n/project name d/date that will be edited

**Expected behavior**
Expected to see a change in the project with edited date. 

**Screenshots**
<img width="1440" alt="Screen Shot 2019-04-03 at 12 39 52 PM" src="https://user-images.githubusercontent.com/35758355/55453264-bc95ac80-560d-11e9-8daf-63f0bbbcc614.png">

**Additional context**

<hr>

**Reported by:** @jemine1998
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#47]</sub>

**Comment by ndhuu** [comment]
This is due to incomplete UG, which has been updated #124
