### ISSUE TITLE
User Guide for addVolunteer is incorrect

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#91]
**Describe the bug**
The examples given in the user are not accepted as valid, and the parameters dietary preference and medical condition are not shown to be optional in the command format given (not bracketed).

**To Reproduce**
1. Go to section 3.3 of the user guide.
2. Copy and paste one of the example inputs given.
3. The input is rejected.

**Expected behavior**
The examples given should be valid inputs.

<hr>

**Reported by:** @justin-ong
**Severity:** Medium

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#71]</sub>

**Comment by swalahlah** [comment]
UG updated. Case closed
