### ISSUE TITLE
find command suggest invalid command

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#92]
**Describe the bug**
With several volunteers added, 'find keyword' command should list volunteers whose name matches the keyword but when this command is executed, result display shows unknown command. 

**To Reproduce**
1. add afew volunteers with addVolunteer command. 
2. execute find command with existing volunteer's name

**Expected behavior**
list of volunteer with name matching keyword should appear

**Screenshots**
<img width="1440" alt="Screen Shot 2019-04-03 at 12 45 19 PM" src="https://user-images.githubusercontent.com/35758355/55453559-fa470500-560e-11e9-9394-d10ceb1f3557.png">

**Additional context**

<hr>

**Reported by:** @jemine1998
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#73]</sub>

**Comment by swalahlah** [comment]
Autosuggest command removed
