### ISSUE TITLE
Delete Volunteers Not Working

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#93]
**Describe the bug**
Added a volunteer into the app, trying to delete this person using , show "Unknown command" and the person trying to be deleted is not deleted. The document is not accurate in the command. Tried "deleteVolunteer" then only work.

**To Reproduce**
1. Go to command box.
2.  Type in "addVolunteer n/John Doe y/22 g/M r/French rg/Christian p/98765432 a/311, Clementi Ave 2, #02-25 e/johnd@example.com ec/Sally Mother 91234567 dp/nil m/nil t/new volunteer"
3. Type in "delete 1"

**Expected behavior**
The person with the index number in the list should be deleted from the list.

<hr>

**Reported by:** @cheahzk
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#78]</sub>

**Comment by swalahlah** [comment]
UG not updated. Command Working
