### ISSUE TITLE
select command suggest invalid command

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#94]
**Describe the bug**
Select command is executed after list / find command. 
List and find command when executed suggest invalid command in the result display.
Select command does not work despite selecting a index that is listed in the volunteer list, it shows invalid command in the result display. 

**To Reproduce**
1. execute 'list' command 
2. execute 'select index' with a index value that is present in the volunteers' list.

**Expected behavior**
The volunteer with selected index should appear.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-04-03 at 12 50 55 PM" src="https://user-images.githubusercontent.com/35758355/55453626-367a6580-560f-11e9-8ddd-0827bbbd55ac.png">

**Additional context**

<hr>

**Reported by:** @jemine1998
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#98]</sub>

**Comment by ndhuu** [comment]
#124
