### ISSUE TITLE
map command suggest invalid command

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#96]
**Describe the bug**
Mapping command should map points to volunteers with different criteria but when map command is executed, the result display shows unknown command.

**To Reproduce**
1. add afew volunteers with addVolunteer command
2. execute map t/value+criteria

**Expected behavior**
Points should be allocated to volunteers who's credentials match the criteria.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-04-03 at 12 58 29 PM" src="https://user-images.githubusercontent.com/35758355/55453869-3c247b00-5610-11e9-99f2-76681488f847.png">

**Additional context**

<hr>

**Reported by:** @jemine1998
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#114]</sub>

**Comment by ndhuu** [comment]
We have fixed this. Thank you
