### ISSUE TITLE
Add command alias for each commands

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#97]
**Please describe the problem**
The commands name are mostly long in length, so it can be troublesome to type everything each time.

**Describe the improvement you'd like to suggest**
Add alias for those commands, like eB for editBeneficiary

<hr>

**Reported by:** @cheahzk
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#117]</sub>

**Comment by ndhuu** [comment]
implemented #123
