### ISSUE TITLE
sort command suggest invalid command 

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#98]
**Describe the bug**
Sort command is suppose to sort volunteers from highest to lowest score.
For volunteers to have points, a map command is executed to allocate them points. Map command as suggested in another issue does not work. Hence bug found in point allocation. Hence nothing to sort.
Sort command when executed also displays invalid command. 

**To Reproduce**
1. execute 'sort' in command line

**Expected behavior**
A sorted list of volunteer with ascending points should be listed.

**Screenshots**
<img width="1440" alt="Screen Shot 2019-04-03 at 12 58 29 PM" src="https://user-images.githubusercontent.com/35758355/55454084-177cd300-5611-11e9-996b-ed5a6d905ec4.png">

**Additional context**

<hr>

**Reported by:** @jemine1998
**Severity:** Low

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#139]</sub>

**Comment by ndhuu** [comment]
We have fixed this. Thank you
