### ISSUE TITLE
editBeneficiary causes unexpected results

### ISSUE THREAD

**Issue by nus-pe-script** [cs2113-ay1819s2-t08-1/main#99]
**Describe the bug**
When using editBeneficiary, changing the index of the beneficiary can result in strange behaviour. For example, editing the first beneficiary's phone number then attempting to edit the second beneficiary's address causes the first edit to be reverted. In addition, sometimes editing a beneficiary can change the parameters of a different beneficiary instead.

**To Reproduce**
1. Add 2 beneficiaries.
2. Edit the first beneficiary's phone number.
3. Edit the second beneficiary's address.
4. The second beneficiary is not updated, and the first beneficiary's phone number is reverted to its original state.

**Expected behavior**
editBeneficiary should edit the indexed beneficiary, and not change anything else.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/35714621/55454206-9540de80-5611-11e9-8988-77b33e21c8c1.PNG)
![Capture1](https://user-images.githubusercontent.com/35714621/55454211-98d46580-5611-11e9-9154-9512b8492af7.PNG)

<hr>

**Reported by:** @justin-ong
**Severity:** High

<sub>[original: nusCS2113-AY1819S2/pe-dry-run#154]</sub>

**Comment by ndhuu** [comment]
fixed. thank you for comments
